# Generated by Django 6.0.1 on 2026-03-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_availability_status_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expert_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='interactions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='salt_composition',
            field=models.CharField(blank=True, help_text='e.g., Paracetamol (500mg)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='side_effects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
