# Generated by Django 6.0.1 on 2026-03-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_email_optional_phone_sms_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Required — Verified via Firebase Phone Auth', max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
